### PR TITLE
Add requirements.txt

### PR DESCRIPTION
**Pull request by keeb-zz**
The downside of distribute is it does/did not install the needed dependencies automatically. In addition, not all dependencies were capture.

With pip, that's taken care of and it integrates seamlessly with a virtualenv.

### CODE REVIEW

**Comment by alunduil** [comment]
It looks like you're listing some dependencies of dependencies.  The list in setup.py should be complete assuming that those dependencies have their requirements.txt filled correctly.  Specific examples:
- Jinja, Weurkzeug, &c are dependencies of flask
- mock and nose should be marked testing dependencies if possible
- os-\* and rackspace-\* are dependencies of pyrax

I thought I had removed the dependency on unittest2 but will re-evaluate.

It's been my understanding (and I haven't played with pip much) that one should only list the first level dependencies of a package and not further levels.  Is this due to those dependencies not listing their dependencies correctly as I suggest above or something else in pip that I'll have to take into account?

**Comment by keeb-zz** [comment]
Thanks for the feedback here as well. You're absolutely right. I have fixed the problems you've mentioned and verified the before and after tests results are identical.

**Comment by keeb-zz** [comment]
I think it's less risky to specify versions, as those can be considered stable versions. I believe that having others have control over whether your application builds (including dependencies) or not is risky!

As for dependencies, django (which has an admittedly huge test list) manages it similarly - they store the reqs in `django/tests/requirements/base.txt` and then optional dependencies based on the integration. Interestingly, they do not specify a version which I disagree with as per above.

**Comment by alunduil** [comment]
Sounds good to me.  If we find we need to remove the versions later we always can.

**Pull request merged**
