### PR TITLE
Fix #11 - get tests to work

### LINKED ISSUE #11: Tests do not currently pass
```
======================================================================
ERROR: Failure: ArgumentError (argument --flask-host: conflicting option string(s): --flask-host)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nose/loader.py", line 413, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/local/lib/python2.7/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/local/lib/python2.7/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/website/margarine/tinge/__init__.py", line 65, in <module>
    "help": "Enable debugging of the flask application.",
  File "/website/margarine/parameters.py", line 163, in __init__
    self._add_argument_parameters(name, parameters)
  File "/website/margarine/parameters.py", line 327, in _add_argument_parameters
    parser.add_argument(*options["args"], **options["kwargs"])
  File "/usr/lib/python2.7/argparse.py", line 1295, in add_argument
    return self._add_action(action)
  File "/usr/lib/python2.7/argparse.py", line 1496, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
  File "/usr/lib/python2.7/argparse.py", line 1309, in _add_action
    self._check_conflict(action)
  File "/usr/lib/python2.7/argparse.py", line 1447, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "/usr/lib/python2.7/argparse.py", line 1454, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
ArgumentError: argument --flask-host: conflicting option string(s): --flask-host

======================================================================
ERROR: Failure: ImportError (No module named api)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nose/loader.py", line 413, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/local/lib/python2.7/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/local/lib/python2.7/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/website/test_margarine/test_unit/test_api/test_article.py", line 13, in <module>
    from margarine.api import information
ImportError: No module named api

======================================================================
ERROR: Failure: ImportError (No module named api)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nose/loader.py", line 413, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/local/lib/python2.7/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/local/lib/python2.7/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/website/test_margarine/test_unit/test_api/test_user.py", line 12, in <module>
    from margarine.api import information
ImportError: No module named api

======================================================================
ERROR: Failure: SyntaxError (invalid syntax (test_users.py, line 50))
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nose/loader.py", line 413, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/local/lib/python2.7/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/local/lib/python2.7/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/website/test_margarine/test_unit/test_consumers/test_users.py", line 50
    self.mock_keyspace.setex.assert_called_once_with(mock.ANY, "test_user", mock.ANY)
       ^
SyntaxError: invalid syntax

----------------------------------------------------------------------
Ran 20 tests in 1.023s

FAILED (errors=5)
```

### PR DESCRIPTION
**Pull request by keeb-zz**
Tests now work but do not pass. Let me know if this is in the right direction and I'll work on getting them to pass.

### CODE REVIEW

**Comment by keeb-zz** [comment]
This is an intermediate step for fixing #11

**Comment by alunduil** [comment]
Thanks for the commits but they're not quite what I'm looking for.  I've provided comments on the individual commits.  Feel free to follow up here or there and we'll get these merged into the test/refactor branch when they're ready.  Thanks again for the time and effort on helping out with this.

**Comment by keeb-zz** [comment]
No problem! That's the whole point of the process. Thanks for the time for providing feedback. I'll incorporate it and resubmit the pull request.

**Comment by keeb-zz** [comment]
OK  - this should be inline with your comments. Let me know :+1: 

The only change I haven't reverted is the tinge one. I'll be happy to remove it completely. The problem is that the argument parsing definitely conflicts. I am not really an expert on it so I do not know why. I can dig in to that.

**Comment by keeb-zz** [comment]
@alunduil fixed as requested.

**Comment by alunduil** [comment]
Pulled into test/refactor for inclusion in massaging of tests to be merged into master later.  Thanks again Nick.

**Pull request closed without merging**
