### PR TITLE
Vagrantfile & Berksfile added for development environment

### PR DESCRIPTION
**Pull request by hhoover**

### CODE REVIEW

**Comment by alunduil** [comment]
Should we mock object storage or implement a box for it?  I see a lot of attributes that have dummy values for pyrax items.

What needs to be fixed in the mongo cookbook again?

Why are the attributes for mongo split across several attributes?  Is it easier to use a URL like the configuration expects?  Same for the queue.

Does this configuration currently handle loading the /vagrant directory as the installation of margarine?

**Comment by hhoover** [comment]
Should we mock object storage or implement a box for it? I see a lot of attributes that have dummy values for pyrax items.

Jason is working on a Swift cookbook / vagrant box. Not sure if Margarine can use Pyrax with a private deployment of Swift, so for the time being it is assumed you will use a Cloud Files account.

What needs to be fixed in the mongo cookbook again?

Nothing. MongoDB gets set up with a database and user.

Why are the attributes for mongo split across several attributes? Is it easier to use a URL like the configuration expects? Same for the queue.

More choice for the user. This can be changed pretty easily if need be. Log an issue and/or trello card.

Does this configuration currently handle loading the /vagrant directory as the installation of margarine?

No. Margarine is deployed using the Margarine cookbook, which uses the git repo for the app.

## 

Hart Hoover

**Comment by alunduil** [comment]
Looks like the only item outstanding on this is getting the current source directory to be used as the installed version of margarine.  I'll open a bug in margarine-chef and start hacking at that using environments as well as update the Vagrantfile with the nodes' environment definition.

Unless, someone can suggest a better solution to this logic that is.

**Comment by alunduil** [comment]
Just heard of chef-zero.  Should we use this when we think about merging this?

**Comment by alunduil** [comment]
Currently awaiting merge of margarine-chef's issues/10 branch.

**Comment by alunduil** [comment]
At this point the environment comes up and responds to all of the items found in production with the exception of having access to swift as an object store.  I'm inclined to let this merge but would like another to test this and verify that it allows for all of the actions of the production environment.  Also, if anyone has any opinion on waiting for swift I would love to hear reasons fro waiting.

**Pull request merged**
